name: Test Schedule

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # 每15分钟一次，先测试能不能触发

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Schedule works! $(date)"
